
spring:
  profiles:
    active: local

---


server:
  port: 8080


spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  output:
    ansi:
      enabled: always
  cache:
    type: redis
  redis:
    port: 6379
    host: localhost


logging:
  level:
    com.hgstudy.jwtbasic: debug